// This file is @generated by prost-build.
/// HandshakeRequest is sent by the client during authentication
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HandshakeRequest {
    /// Client timestamp for replay protection
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    /// Client's public key (33 bytes compressed)
    #[prost(bytes = "vec", tag = "2")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
    /// ECDSA signature over timestamp
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    /// Optional client identifier
    #[prost(string, tag = "4")]
    pub client_id: ::prost::alloc::string::String,
    /// Random nonce for replay protection
    #[prost(bytes = "vec", tag = "5")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// HandshakeResponse is sent from the server to the client after a handshake request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HandshakeResponse {
    /// Whether authentication succeeded
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    /// Error message if rejected
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    /// Unique session identifier
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
}
/// Ping is sent to check connection liveness
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Ping {
    /// Timestamp for latency measurement
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
}
/// Pong is a response to a Ping message
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Pong {
    /// Echo back the timestamp from Ping
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
}
/// DisconnectMessage is sent when gracefully closing a connection
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisconnectMessage {
    /// Disconnect reason code
    #[prost(enumeration = "disconnect_message::Reason", tag = "1")]
    pub reason: i32,
    /// Human-readable details (optional)
    #[prost(string, tag = "2")]
    pub details: ::prost::alloc::string::String,
}
/// Nested message and enum types in `DisconnectMessage`.
pub mod disconnect_message {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Reason {
        /// Client or server requested disconnect
        Requested = 0,
        /// Protocol violation detected
        ProtocolError = 1,
        /// Connection limit reached
        TooManyPeers = 2,
        /// Authentication failed
        AuthFailure = 3,
        /// Read operation timed out
        ReadTimeout = 4,
        /// Write operation timed out
        WriteTimeout = 5,
        /// Network-level error
        NetworkError = 6,
        /// Internal server error
        InternalError = 7,
        /// Connection throttled (rate limited)
        Throttled = 8,
    }
    impl Reason {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Requested => "REQUESTED",
                Self::ProtocolError => "PROTOCOL_ERROR",
                Self::TooManyPeers => "TOO_MANY_PEERS",
                Self::AuthFailure => "AUTH_FAILURE",
                Self::ReadTimeout => "READ_TIMEOUT",
                Self::WriteTimeout => "WRITE_TIMEOUT",
                Self::NetworkError => "NETWORK_ERROR",
                Self::InternalError => "INTERNAL_ERROR",
                Self::Throttled => "THROTTLED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "REQUESTED" => Some(Self::Requested),
                "PROTOCOL_ERROR" => Some(Self::ProtocolError),
                "TOO_MANY_PEERS" => Some(Self::TooManyPeers),
                "AUTH_FAILURE" => Some(Self::AuthFailure),
                "READ_TIMEOUT" => Some(Self::ReadTimeout),
                "WRITE_TIMEOUT" => Some(Self::WriteTimeout),
                "NETWORK_ERROR" => Some(Self::NetworkError),
                "INTERNAL_ERROR" => Some(Self::InternalError),
                "THROTTLED" => Some(Self::Throttled),
                _ => None,
            }
        }
    }
}
/// XtID represents a transaction ID (SHA256 hash)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct XtId {
    /// 32-byte SHA256 hash
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
/// XTRequest represents a cross-chain transaction request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct XtRequest {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<TransactionRequest>,
}
/// TransactionRequest represents a single transaction request for a specific chain
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub chain_id: ::prost::alloc::vec::Vec<u8>,
    /// RLP encoded Ethereum transactions
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub transaction: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// Vote is a 2PC vote message from a sequencer to the SP
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vote {
    /// Which chain is voting
    #[prost(bytes = "vec", tag = "1")]
    pub sender_chain_id: ::prost::alloc::vec::Vec<u8>,
    /// Transaction ID
    #[prost(message, optional, tag = "2")]
    pub xt_id: ::core::option::Option<XtId>,
    /// true = Commit, false = Abort
    #[prost(bool, tag = "3")]
    pub vote: bool,
}
/// Decided is a 2PC decision message from the SP to sequencers
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Decided {
    /// Transaction ID
    #[prost(message, optional, tag = "1")]
    pub xt_id: ::core::option::Option<XtId>,
    /// true = Commit, false = Abort
    #[prost(bool, tag = "2")]
    pub decision: bool,
}
/// CIRCMessage for direct message exchange between sequencers
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CircMessage {
    #[prost(bytes = "vec", tag = "1")]
    pub source_chain: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub destination_chain: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub source: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub receiver: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "5")]
    pub xt_id: ::core::option::Option<XtId>,
    #[prost(string, tag = "6")]
    pub label: ::prost::alloc::string::String,
    /// ABI encoded data
    #[prost(bytes = "vec", repeated, tag = "7")]
    pub data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// 32-byte big-endian session identifier (U256)
    #[prost(bytes = "vec", tag = "8")]
    pub session_id: ::prost::alloc::vec::Vec<u8>,
}
/// L2BlockRequest specifies which L2 block a sequencer should build
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct L2BlockRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub chain_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub block_number: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
}
/// StartSlot is sent by SP to begin a new slot
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartSlot {
    /// Current slot number
    #[prost(uint64, tag = "1")]
    pub slot: u64,
    /// Superblock number SP aims to produce
    #[prost(uint64, tag = "2")]
    pub next_superblock_number: u64,
    /// Hash of the last valid superblock
    #[prost(bytes = "vec", tag = "3")]
    pub last_superblock_hash: ::prost::alloc::vec::Vec<u8>,
    /// L2 blocks to be built by each rollup
    #[prost(message, repeated, tag = "4")]
    pub l2_blocks_request: ::prost::alloc::vec::Vec<L2BlockRequest>,
}
/// RequestSeal is sent by SP to request sequencers seal their blocks
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestSeal {
    /// Current slot number
    #[prost(uint64, tag = "1")]
    pub slot: u64,
    /// List of included cross-chain transaction IDs
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub included_xts: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// RollBackAndStartSlot is sent by SP to rollback and restart from a valid state
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RollBackAndStartSlot {
    /// L2 blocks to build from valid state
    #[prost(message, repeated, tag = "1")]
    pub l2_blocks_request: ::prost::alloc::vec::Vec<L2BlockRequest>,
    /// Current slot number
    #[prost(uint64, tag = "2")]
    pub current_slot: u64,
    /// Next superblock number to produce
    #[prost(uint64, tag = "3")]
    pub next_superblock_number: u64,
    /// Hash of last valid superblock
    #[prost(bytes = "vec", tag = "4")]
    pub last_superblock_hash: ::prost::alloc::vec::Vec<u8>,
}
/// L2Block is submitted from sequencer to SP
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct L2Block {
    /// Slot this block belongs to
    #[prost(uint64, tag = "1")]
    pub slot: u64,
    /// Chain identifier
    #[prost(bytes = "vec", tag = "2")]
    pub chain_id: ::prost::alloc::vec::Vec<u8>,
    /// L2 block number
    #[prost(uint64, tag = "3")]
    pub block_number: u64,
    /// Hash of this L2 block
    #[prost(bytes = "vec", tag = "4")]
    pub block_hash: ::prost::alloc::vec::Vec<u8>,
    /// Hash of parent L2 block
    #[prost(bytes = "vec", tag = "5")]
    pub parent_block_hash: ::prost::alloc::vec::Vec<u8>,
    /// Included cross-chain transaction IDs
    #[prost(bytes = "vec", repeated, tag = "6")]
    pub included_xts: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Encoded Ethereum block data (RLP encoded)
    #[prost(bytes = "vec", tag = "7")]
    pub block: ::prost::alloc::vec::Vec<u8>,
}
/// StartSC is sent by SP to start cross-chain transaction coordination
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartSc {
    /// Current slot number
    #[prost(uint64, tag = "1")]
    pub slot: u64,
    /// Sequence number for ordering within slot
    #[prost(uint64, tag = "2")]
    pub xt_sequence_number: u64,
    /// The cross-chain transaction request
    #[prost(message, optional, tag = "3")]
    pub xt_request: ::core::option::Option<XtRequest>,
    /// 32-byte SHA256 hash over xTRequest
    #[prost(bytes = "vec", tag = "4")]
    pub xt_id: ::prost::alloc::vec::Vec<u8>,
}
/// Block submission from a sequencer to the SP (deprecated, kept for backward compatibility)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    /// Which chain's block
    #[prost(bytes = "vec", tag = "1")]
    pub chain_id: ::prost::alloc::vec::Vec<u8>,
    /// The actual block data
    #[prost(bytes = "vec", tag = "2")]
    pub block_data: ::prost::alloc::vec::Vec<u8>,
    /// Which xTs are included
    #[prost(message, repeated, tag = "3")]
    pub included_xt_ids: ::prost::alloc::vec::Vec<XtId>,
}
/// Message is the main wrapper for all protocol messages
/// This allows multiplexing different message types over a single connection
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// Identifier of the sender
    #[prost(string, tag = "1")]
    pub sender_id: ::prost::alloc::string::String,
    /// Payload contains the actual message content
    #[prost(
        oneof = "message::Payload",
        tags = "2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16"
    )]
    pub payload: ::core::option::Option<message::Payload>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    /// Payload contains the actual message content
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// SCP (Synchronous Composability Protocol) messages
        #[prost(message, tag = "2")]
        XtRequest(super::XtRequest),
        #[prost(message, tag = "3")]
        Vote(super::Vote),
        #[prost(message, tag = "4")]
        Decided(super::Decided),
        /// Deprecated
        #[prost(message, tag = "5")]
        Block(super::Block),
        #[prost(message, tag = "6")]
        CircMessage(super::CircMessage),
        /// SBCP (Superblock Construction Protocol) messages
        #[prost(message, tag = "7")]
        StartSlot(super::StartSlot),
        #[prost(message, tag = "8")]
        RequestSeal(super::RequestSeal),
        #[prost(message, tag = "9")]
        RollBackAndStartSlot(super::RollBackAndStartSlot),
        #[prost(message, tag = "10")]
        L2Block(super::L2Block),
        #[prost(message, tag = "11")]
        StartSc(super::StartSc),
        /// Transport-level messages
        #[prost(message, tag = "12")]
        HandshakeRequest(super::HandshakeRequest),
        #[prost(message, tag = "13")]
        HandshakeResponse(super::HandshakeResponse),
        #[prost(message, tag = "14")]
        Ping(super::Ping),
        #[prost(message, tag = "15")]
        Pong(super::Pong),
        #[prost(message, tag = "16")]
        Disconnect(super::DisconnectMessage),
    }
}
