[package]
name = "sidecar-publisher"
version = "0.1.0"
description = "Publisher client connection for SP communication"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sidecar-primitives-traits.workspace = true
ethera-spec.workspace = true
ethera-spec-proto.workspace = true
sidecar-transport.workspace = true
bytes.workspace = true
prost.workspace = true
async-trait.workspace = true
