[package]
name = "sidecar-primitives-traits"
version = "0.1.0"
description = "Shared traits and error types for sidecar coordination"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
alloy.workspace = true
sidecar-primitives.workspace = true
ethera-spec.workspace = true
ethera-spec-proto.workspace = true
async-trait.workspace = true
thiserror.workspace = true
